### ISSUE TITLE
Mocks

### ISSUE THREAD

**Issue by Sorong** [Sorong/health-ledger-frontend#2]
mock-requests.ts - spiegelt ja die Anfragen wider (?), allerdings habe ich ein Problem mit der RequestForm ich bin verwirrt mit den beinhalteten Informationen... Die Info sind ja für dieses Mockup (?): [hier](https://github.com/SGSE18/health-ledger/raw/master/pflichtenheft/images/arztversicherungapothekerarbeitgeber_einsichtsanfragendetails.png) oder für dieses [hier](https://github.com/SGSE18/health-ledger/raw/master/pflichtenheft/images/patient_einsichtsanfragendetails.png) - was ist der Grund für die "note" wo kommt das her und was ist das? und was ist beim Result "reason" ? 
Wäre super wenn ihr entweder den Datentyp anpasst oder uns mitteilt was wir wo anpassen müssen. Und ist reject dann auch "closed" und kann nachträglich nicht angenommen werden? 

mock-SmartPerscription.ts - ähnliche Ausgangsfrage... zu wem gehört das jetzt...zum Arzt oder zum Patienten... ich gehe vom Patienten aus (?) dann passt beim Mock nicht, dass der Patientenname unterschiedlich ist...sollte ja immer der user sein. Frage vorsichtshalber, nicht dass ich das Ding als Basis für die falsche Komponente nehme.

Wäre es eventuell möglich, dass ihr bei den Datenklassen als Kommentar den Link zum Mockupbild hinzufügt um Missverständnisse zu vermeiden, sonst machen entweder wir uns oder ihr euch doppelte Arbeit.

**Comment by Exormeter** [comment]
Note ist einfach ein freies Feld für Notizen, falls der Arzt\Versicherung\Antragsteller dem Patienten mitteilen möchte, weshalb die Infos gebraucht werden. Falls ihr das nicht umsetzten wollt ist das auch ok, sollte für das System nicht wichtig sein. Wäre einfach Qol für die Teilnehmer im System. 

Reason im Resultobjekt ist ein ähnlicher Sachverhalt, damit könnte der Patient kommunizieren, weshalb er die Freigabe verweigert hat. Kann theoretisch und auch praktisch leer bleiben. 

Das Rejected Feld ist nur Status ob die Anfrage vom Patienten genehmigt worden ist oder nicht. 

Das SmartPerscription wird vom Artz in einer Behandlung ausgestellt und zur Behandlung hinzugefügt (treatment). Dannach wird es in die Krankenakte des Patienten gelegt. Das SmartPerscription gehört immer zu einem User, daher ist der Name theoretisch überflüssig. Aber wir hatten doch beim reszept sowieso gesagt das wir jetzt nur das Note Feld benutzen, oder nicht?

**Comment by Sorong** [comment]
ah in Ordnung verstehe...dann kann ich das integrieren. War mir nicht sicher wo es hin sollte.

Beim Rezept habe ich nochmal mit Fynn gesprochen, eventuell (wahrscheinlich) werden wir die Felder nutzen und die Viewcomponenten anpassen. 

Wäre aber trotzdem super wenn ihr als Kommentar eure Zuordnung hinschreiben könntet, dann sparen wa uns vermutlich den ein oder anderen Issue.^^

**Comment by Sorong** [comment]
Brauch noch nen Timestamp in der RequestForm

**Comment by Exormeter** [comment]
Wofür? Kann sein das du Duration nehmen kannst

**Comment by Sorong** [comment]
Fürs Datum tatsächlich... aber Problem is nen anderes (hatte Cem wegen was mit dem Routing gefragt), ich brauch keine Liste mit Verschreibungen sondern ne Liste mit Behandlungen die dann die Verschreibungen beinhalten... so kann ich die Detailansichten eines Rezeptes mit der Id der Behandlung generieren.

**Comment by Exormeter** [comment]
Hatte mir schon gedacht das du dass du darauf stößt, du hast recht, es gibt keine einzelne Verschreibungen oder Atteste. Ich mocke den RestService morgen richtig, dann kannst du damit besser arbeiten. 

Hier ist der aktuelle RestService als Doku und was woran du alles drankommen kannst:
https://app.swaggerhub.com/apis/health-ledger-rest/Health-Ledger-RestService/1.0.0
